version: '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      - "TZ=Europe/Amsterdam"
      - "POSTGRES_USER=root"
      - "POSTGRES_PASSWORD=root"
      - "POSTGRES_DB=demodb"
    ports:
      - 45432:5432
    volumes:
      - ./sql:/docker-entrypoint-initdb.d